//
//  GhosttyLayeredConfigComposer.swift
//  AgentHub
//

import AgentHubCore
import Foundation

/// Resolves the config path handed to the embedded Ghostty runtime.
///
/// libghostty's `ghostty_config_load_file` treats the given file as the
/// *entire* base config — the user's default Ghostty config files are then
/// skipped. That "replace" semantic surprises users: pointing AgentHub at a
/// small tweak file silently disables their real Ghostty config.
///
/// This composer turns the setting into an *override* instead. When a custom
/// file is configured, it writes a generated config whose only content is
/// ordered `config-file` includes — the user's default Ghostty config files
/// first (mirroring Ghostty's own load order: XDG, then Application Support),
/// the custom file last so it wins. `ghostty_config_load_recursive_files`
/// resolves the includes; the `?` prefix makes missing files a no-op.
///
/// AgentHub's appearance overlay is applied after all of this at the runtime
/// and surface layers, so it still has the final word on background blending
/// and light-mode legibility.
public enum GhosttyLayeredConfigComposer {

  /// Returns the path the embedded runtime should load, or nil to let
  /// libghostty load the user's default Ghostty config files itself.
  ///
  /// With a valid custom file configured, returns the generated layered
  /// config's path. If the generated file cannot be written, degrades to the
  /// custom path directly (old replace semantics) rather than dropping it.
  public static func effectiveConfigPath(
    defaults: UserDefaults = .standard,
    fileManager: FileManager = .default,
    environment: [String: String] = ProcessInfo.processInfo.environment,
    homeDirectoryURL: URL? = nil,
    outputDirectoryURL: URL? = nil
  ) -> String? {
    guard let customPath = GhosttyConfigPathResolver.configuredPath(
      defaults: defaults,
      fileManager: fileManager
    ) else {
      return nil
    }

    let content = layeredConfigContent(
      customPath: customPath,
      environment: environment,
      homeDirectoryURL: homeDirectoryURL ?? fileManager.homeDirectoryForCurrentUser
    )

    let outputDirectory = outputDirectoryURL
      ?? ClaudeHookPaths.appSupportBaseURL.appendingPathComponent("ghostty", isDirectory: true)
    let outputURL = outputDirectory.appendingPathComponent("embedded-config", isDirectory: false)

    do {
      try fileManager.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
      try content.write(to: outputURL, atomically: true, encoding: .utf8)
      return outputURL.path
    } catch {
      return customPath
    }
  }

  /// The generated file body: default config locations first, custom file
  /// last. Exposed for tests.
  static func layeredConfigContent(
    customPath: String,
    environment: [String: String],
    homeDirectoryURL: URL
  ) -> String {
    var lines = [
      "# Generated by AgentHub — do not edit.",
      "# Layers the custom Ghostty config from AgentHub Settings on top of",
      "# the default Ghostty config files.",
    ]
    for path in defaultConfigPaths(environment: environment, homeDirectoryURL: homeDirectoryURL)
    where path != customPath {
      lines.append("config-file = ?\(path)")
    }
    lines.append("config-file = ?\(customPath)")
    return lines.joined(separator: "\n") + "\n"
  }

  /// Ghostty's default config locations on macOS, in Ghostty's own load
  /// order (Application Support last, so it takes precedence over XDG).
  static func defaultConfigPaths(
    environment: [String: String],
    homeDirectoryURL: URL
  ) -> [String] {
    let xdgBase: URL
    if let xdgConfigHome = environment["XDG_CONFIG_HOME"], !xdgConfigHome.isEmpty {
      xdgBase = URL(fileURLWithPath: (xdgConfigHome as NSString).expandingTildeInPath, isDirectory: true)
    } else {
      xdgBase = homeDirectoryURL.appendingPathComponent(".config", isDirectory: true)
    }

    return [
      xdgBase
        .appendingPathComponent("ghostty", isDirectory: true)
        .appendingPathComponent("config", isDirectory: false)
        .path,
      homeDirectoryURL
        .appendingPathComponent("Library", isDirectory: true)
        .appendingPathComponent("Application Support", isDirectory: true)
        .appendingPathComponent("com.mitchellh.ghostty", isDirectory: true)
        .appendingPathComponent("config", isDirectory: false)
        .path,
    ]
  }
}
