import Foundation

/// The Swift package AgentHub materializes on disk and builds (once, cached)
/// to produce the simulator-side support dylibs:
///
/// - `AgentHubPreviewHost.framework` — our own preview host: SnapshotPreviews'
///   discovery + rendering core behind the same HTTP contract as its stock
///   `Snapshotting` dylib, but rendering with the windowless
///   `SwiftUIRenderingStrategy`. The stock dylib is built for headless
///   snapshot runs — its `UIKitRenderingStrategy` covers the live app with a
///   full-screen system-background window, which is exactly what we must not
///   do next to the Live mirror.
/// - `AgentHubInjection.framework` — embeds InjectionLite (`-all_load` keeps
///   its `+load` boot constructor), the standalone hot-reload engine.
///
/// Both dylibs also link a C boot target whose constructor line-buffers
/// stdout: `simctl launch --stdout=<file>` redirects to a file, which libc
/// fully buffers, so without this the injection engine's log lines (our
/// reload-confirmation signal) sit unflushed for kilobytes at a time.
///
/// Both upstream dependencies are pinned to exact released versions; the
/// console parser and launch-environment contracts are written against these
/// versions, so bump them together.
public enum HotReloadHostPackage {

  public static let snapshotPreviewsVersion = "0.16.0"
  public static let injectionLiteVersion = "2.1.2"
  /// Must match SnapshotPreviews' own exact FlyingFox pin — our preview host
  /// target depends on it directly for the HTTP server.
  public static let flyingFoxVersion = "0.16.0"

  public static let packageName = "AgentHubHotReloadHost"
  public static let previewHostScheme = "AgentHubPreviewHost"
  public static let injectionScheme = "AgentHubInjection"

  /// The environment variable (forwarded via `SIMCTL_CHILD_`) that arms the
  /// preview host inside the app.
  public static let previewHostEnvironmentKey = "AGENTHUB_PREVIEW_HOST"

  /// Identifies the generated package + pins; cached build artifacts are
  /// invalidated when this changes.
  public static var fingerprint: String {
    "snapshot-previews-\(snapshotPreviewsVersion)_injection-lite-\(injectionLiteVersion)_v3"
  }

  public static var manifest: String {
    """
    // swift-tools-version: 5.9
    // Generated by AgentHub — do not edit. Regenerated when pins change.
    import PackageDescription

    let package = Package(
      name: "\(packageName)",
      platforms: [.iOS(.v15)],
      products: [
        .library(
          name: "\(previewHostScheme)",
          type: .dynamic,
          targets: ["\(previewHostScheme)"]
        ),
        .library(
          name: "\(injectionScheme)",
          type: .dynamic,
          targets: ["\(injectionScheme)"]
        ),
      ],
      dependencies: [
        .package(
          url: "https://github.com/getsentry/SnapshotPreviews.git",
          exact: "\(snapshotPreviewsVersion)"
        ),
        .package(
          url: "https://github.com/johnno1962/InjectionLite.git",
          exact: "\(injectionLiteVersion)"
        ),
        .package(
          url: "https://github.com/swhitty/FlyingFox.git",
          exact: "\(flyingFoxVersion)"
        ),
      ],
      targets: [
        // Shared C constructor: line-buffer stdout so engine logs reach the
        // redirected console file immediately.
        .target(name: "CAgentHubUnbuffer"),
        // Preview-host-only C constructor: starts the host when the
        // AGENTHUB_PREVIEW_HOST environment variable is set.
        .target(name: "CAgentHubPreviewBoot"),
        .target(
          name: "\(previewHostScheme)",
          dependencies: [
            "CAgentHubUnbuffer",
            "CAgentHubPreviewBoot",
            .product(name: "SnapshotPreviewsCore", package: "SnapshotPreviews"),
            .product(name: "FlyingFox", package: "FlyingFox"),
          ]
        ),
        .target(
          name: "\(injectionScheme)",
          dependencies: [
            "CAgentHubUnbuffer",
            .product(name: "InjectionLite", package: "InjectionLite"),
          ],
          linkerSettings: [
            // Pull every InjectionLite object into this dylib so its
            // `+load` boot (InjectionBoot.mm) survives linking.
            .unsafeFlags(["-Xlinker", "-all_load"])
          ]
        ),
      ]
    )
    """
  }

  /// relative path → file content for every generated source file.
  public static var sourceFiles: [String: String] {
    [
      "Sources/CAgentHubUnbuffer/include/CAgentHubUnbuffer.h": """
      // Intentionally empty — the target only contributes a constructor.
      """,

      "Sources/CAgentHubUnbuffer/unbuffer.c": """
      // stdout redirected to a file is fully buffered by libc; the injection
      // engine's log lines are AgentHub's reload-confirmation signal, so
      // switch to line buffering as soon as this dylib loads.
      #include <stdio.h>

      __attribute__((constructor)) static void agenthub_unbuffer_stdout(void) {
        setvbuf(stdout, NULL, _IOLBF, 0);
      }
      """,

      "Sources/CAgentHubPreviewBoot/include/CAgentHubPreviewBoot.h": """
      // Intentionally empty — the target only contributes a constructor.
      """,

      "Sources/CAgentHubPreviewBoot/boot.c": """
      // Boots the Swift preview host when AgentHub armed it for this launch.
      // Lives in C because Swift has no load-time constructors; the callee is
      // resolved at link time since both objects are in the same dylib.
      #include <stdlib.h>

      extern void agenthub_preview_host_start(void);

      __attribute__((constructor)) static void agenthub_preview_boot(void) {
        if (getenv("\(previewHostEnvironmentKey)")) {
          agenthub_preview_host_start();
        }
      }
      """,

      "Sources/\(previewHostScheme)/\(previewHostScheme).swift": previewHostSource,

      "Sources/\(injectionScheme)/\(injectionScheme).swift": """
      // Anchor for the \(injectionScheme) dynamic product. InjectionLite is
      // linked in with -all_load and boots itself via +load when the dylib
      // is inserted with DYLD_INSERT_LIBRARIES.
      let agentHubInjectionAnchor = true
      """,
    ]
  }

  /// The preview host. Serves SnapshotPreviews' HTTP contract (`GET /file`
  /// manifest + `GET /display/{type}/{id}` render) on loopback port 38824,
  /// rendering with the windowless `SwiftUIRenderingStrategy` so the running
  /// app's UI is never covered.
  private static var previewHostSource: String {
    #"""
    #if canImport(UIKit) && DEBUG
    import FlyingFox
    import Foundation
    import SnapshotPreviewsCore
    import SwiftUI
    import UIKit

    /// Called by the CAgentHubPreviewBoot constructor at dylib load time.
    @_cdecl("agenthub_preview_host_start")
    public func agenthub_preview_host_start() {
      guard #available(iOS 16.0, *) else {
        print("AgentHubPreviewHost: previews require an iOS 16+ simulator")
        return
      }
      Task { @MainActor in
        AgentHubPreviewHost.startIfNeeded()
      }
    }

    @available(iOS 16.0, *)
    @MainActor
    final class AgentHubPreviewHost {

      static var shared: AgentHubPreviewHost?

      static func startIfNeeded() {
        guard shared == nil else { return }
        let host = AgentHubPreviewHost()
        shared = host
        // The renderer needs a foreground app; defer until active.
        if UIApplication.shared.applicationState == .active {
          host.start()
        } else {
          NotificationCenter.default.addObserver(
            forName: UIApplication.didBecomeActiveNotification,
            object: nil,
            queue: .main
          ) { _ in
            Task { @MainActor in shared?.start() }
          }
        }
      }

      private let server = HTTPServer(address: .loopback(port: 38824))
      private var serverTask: Task<Void, Never>?

      private static var resultsDirectory: URL {
        FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
          .appendingPathComponent("AgentHubPreviews", isDirectory: true)
      }

      private func start() {
        guard serverTask == nil else { return }
        serverTask = Task {
          do {
            await server.appendRoute("GET /file") { _ in
              let directory = await Self.writeManifest()
              return HTTPResponse(
                statusCode: .ok, body: directory.path.data(using: .utf8) ?? Data())
            }
            await server.appendRoute("GET /display/*") { [weak self] request in
              let components = request.path.components(separatedBy: "/")
              guard let self, components.count > 3 else {
                return HTTPResponse(statusCode: .badRequest)
              }
              let typeName = components[2].removingPercentEncoding ?? components[2]
              let body = await self.renderPreview(typeName: typeName, id: components[3])
              return HTTPResponse(statusCode: .ok, body: body)
            }
            try await server.start()
          } catch {
            print("AgentHubPreviewHost: server failed to start: \(error)")
          }
        }
        print("AgentHubPreviewHost: serving previews on loopback port 38824")
      }

      /// Rewrites the manifest of all discovered preview types.
      @MainActor
      private static func writeManifest() -> URL {
        let directory = resultsDirectory
        try? FileManager.default.removeItem(at: directory)
        try? FileManager.default.createDirectory(
          at: directory, withIntermediateDirectories: true)

        let previewTypes = FindPreviews.findPreviews()
        let manifest = previewTypes.map { preview -> [String: Any] in
          var entry: [String: Any] = [
            "typeName": preview.typeName,
            "numPreviews": preview.previews.count,
          ]
          if let fileID = preview.fileID {
            var name = fileID
            if let displayName = preview.previews.first?.displayName {
              name = "\(fileID):\(displayName)"
            }
            entry["displayName"] = name
          }
          return entry
        }
        if let data = try? JSONSerialization.data(withJSONObject: manifest) {
          try? data.write(to: directory.appendingPathComponent("metadata.json"))
        }
        return directory
      }

      /// Renders one preview to a PNG on the shared filesystem and returns
      /// JSON: {displayName?, imagePath?, scale?, error?}. Rendering uses a
      /// plain ImageRenderer at the device's screen scale — ImageRenderer
      /// defaults to 1x, which is why unscaled snapshots look blurry — and
      /// `scale` lets the host display the image at its true point size.
      @MainActor
      private func renderPreview(typeName: String, id: String) async -> Data {
        var result: [String: Any] = [:]
        let previewTypes = FindPreviews.findPreviews(
          shouldInclude: { name, _ in name == typeName })
        guard let previewType = previewTypes.first(where: { $0.typeName == typeName }),
              let preview = previewType.previews.first(where: { $0.previewId == id })
        else {
          result["error"] = "Preview \(typeName)/\(id) not found"
          return (try? JSONSerialization.data(withJSONObject: result)) ?? Data()
        }
        if let displayName = preview.displayName {
          result["displayName"] = displayName
        }

        let scale = UIScreen.main.scale
        let renderer = ImageRenderer(content: AnyView(preview.view()))
        renderer.scale = scale
        if let image = renderer.uiImage, let data = image.pngData() {
          let file = Self.resultsDirectory
            .appendingPathComponent("\(typeName)-\(id).png")
          try? FileManager.default.createDirectory(
            at: Self.resultsDirectory, withIntermediateDirectories: true)
          do {
            try data.write(to: file)
            result["imagePath"] = file.path
            result["scale"] = Double(scale)
          } catch {
            result["error"] = "Failed to write \(file.path)"
          }
        } else {
          result["error"] = "Could not render \(typeName) — previews that "
            + "depend on UIKit wrappers or runtime context may not be renderable"
        }
        return (try? JSONSerialization.data(withJSONObject: result)) ?? Data()
      }
    }
    #endif
    """#
  }

  /// Writes (or refreshes) the package at `directory`. Idempotent: files are
  /// only rewritten when content changed, so SwiftPM caches stay warm.
  @discardableResult
  public static func write(
    to directory: URL,
    fileManager: FileManager = .default
  ) throws -> Bool {
    var didChange = false
    didChange = try writeIfNeeded(
      manifest,
      to: directory.appendingPathComponent("Package.swift"),
      fileManager: fileManager
    ) || didChange

    for (relativePath, content) in sourceFiles {
      let fileURL = directory.appendingPathComponent(relativePath)
      didChange = try writeIfNeeded(
        content, to: fileURL, fileManager: fileManager
      ) || didChange
    }
    return didChange
  }

  private static func writeIfNeeded(
    _ content: String,
    to url: URL,
    fileManager: FileManager
  ) throws -> Bool {
    if let existing = try? String(contentsOf: url, encoding: .utf8),
       existing == content {
      return false
    }
    try fileManager.createDirectory(
      at: url.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    try content.write(to: url, atomically: true, encoding: .utf8)
    return true
  }
}
